# This file helps build or display printable PDF versions of a CV.

"""Classic CV PDF rendering utilities."""

from django.http import HttpResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from .pdf_helpers import draw_bullets, draw_footer, draw_section


def render_classic_pdf(cv, watermark=False):
    """Render a classic-style CV layout as a PDF response."""
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        f'attachment; filename="{cv.full_name}_Classic_CV.pdf"'
    )

    pdf = canvas.Canvas(response, pagesize=A4)
    width, height = A4

    margin = 55
    content_width = width - (margin * 2)
    y = height - 58

    pdf.setFillColor(colors.HexColor("#111827"))
    pdf.setFont("Times-Bold", 27)
    pdf.drawCentredString(
        width / 2,
        y,
        (cv.full_name or "No Name").replace(" - Tailored CV", ""),
    )

    y -= 24
    pdf.setFont("Times-Roman", 13)
    pdf.drawCentredString(width / 2, y, cv.job_title or "")

    y -= 20
    pdf.setFont("Helvetica", 9)

    contact = " | ".join(item for item in [cv.email, cv.phone, cv.address] if item)

    pdf.drawCentredString(width / 2, y, contact)

    y -= 24
    pdf.setStrokeColor(colors.HexColor("#111827"))
    pdf.setLineWidth(1)
    pdf.line(margin, y, width - margin, y)

    y -= 32

    y = draw_section(
        pdf,
        "Professional Summary",
        cv.professional_summary,
        margin,
        y,
        content_width,
        title_color="#111827",
    )

    y = draw_section(
        pdf,
        "Experience",
        cv.experience,
        margin,
        y,
        content_width,
        title_color="#111827",
    )

    y = draw_section(
        pdf,
        "Education",
        cv.education,
        margin,
        y,
        content_width,
        title_color="#111827",
    )

    pdf.setFillColor(colors.HexColor("#111827"))
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(margin, y, "SKILLS")

    y -= 8
    pdf.setStrokeColor(colors.HexColor("#d1d5db"))
    pdf.line(margin, y, width - margin, y)

    y -= 18
    y = draw_bullets(pdf, cv.skills, margin, y, content_width)

    draw_footer(pdf, width, "Generated by AI CV Builder - Classic Template")
    pdf.save()

    return response
