# This file helps build or display printable PDF versions of a CV.

"""Executive CV PDF rendering utilities."""

from django.http import HttpResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from .pdf_helpers import draw_bullets, draw_footer, draw_section


def render_executive_pdf(cv, watermark=False):
    """Render the executive-style CV template as a PDF response."""
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        f'attachment; filename="{cv.full_name}_Executive_CV.pdf"'
    )

    pdf = canvas.Canvas(response, pagesize=A4)
    width, height = A4

    navy = colors.HexColor("#071f3d")
    gold = colors.HexColor("#d4af37")
    text = colors.HexColor("#111827")

    header_height = 118

    pdf.setFillColor(navy)
    pdf.rect(0, height - header_height, width, header_height, fill=True, stroke=False)

    pdf.setFillColor(gold)
    pdf.rect(0, height - header_height, width, 5, fill=True, stroke=False)

    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 28)
    pdf.drawCentredString(
        width / 2,
        height - 45,
        (cv.full_name or "No Name").replace(" - Tailored CV", ""),
    )

    pdf.setFont("Helvetica", 13)
    pdf.drawString(50, height - 74, cv.job_title or "")

    contact = " | ".join(item for item in [cv.email, cv.phone, cv.address] if item)

    pdf.setFont("Helvetica", 9)
    pdf.drawString(50, height - 96, contact[:95])

    left_x = 50
    right_x = 245
    left_width = 160
    right_width = width - right_x - 50

    y_left = height - 155
    y_right = height - 155

    pdf.setFillColor(text)

    y_left = draw_section(
        pdf,
        "Professional Profile",
        cv.professional_summary,
        left_x,
        y_left,
        left_width,
        title_color="#d4af37",
    )

    pdf.setFillColor(text)
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(left_x, y_left, "CORE SKILLS")

    y_left -= 8
    pdf.setStrokeColor(gold)
    pdf.line(left_x, y_left, left_x + left_width, y_left)

    y_left -= 18
    y_left = draw_bullets(
        pdf,
        cv.skills,
        left_x,
        y_left,
        left_width,
        font_size=9,
        line_height=12,
    )

    y_right = draw_section(
        pdf,
        "Professional Experience",
        cv.experience,
        right_x,
        y_right,
        right_width,
        title_color="#071f3d",
    )

    y_right = draw_section(
        pdf,
        "Education",
        cv.education,
        right_x,
        y_right,
        right_width,
        title_color="#071f3d",
    )

    draw_footer(pdf, width, "Generated by AI CV Builder - Executive Template")
    pdf.save()

    return response
