from django.http import HttpResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def render_classic_pdf(cv):
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = f'attachment; filename="{cv.full_name}_Classic_CV.pdf"'

    p = canvas.Canvas(response, pagesize=A4)
    width, height = A4

    x = 60
    y = height - 60

    # -------------------------
    # HEADER (Classic style)
    # -------------------------
    p.setFont("Times-Bold", 20)
    p.drawString(x, y, cv.full_name or "No Name")

    y -= 25

    p.setFont("Times-Roman", 12)
    p.drawString(x, y, cv.job_title or "")

    y -= 10
    p.line(x, y, width - 60, y)

    y -= 30

    # -------------------------
    # SECTION HELPER
    # -------------------------
    def section(title, text):
        nonlocal y

        # Section title
        p.setFont("Times-Bold", 14)
        p.drawString(x, y, title)

        y -= 18

        p.setFont("Times-Roman", 10)

        if text:
            for line in text.split("\n"):
                clean = line.strip()
                if clean:
                    p.drawString(x, y, clean[:120])
                    y -= 14
        else:
            p.drawString(x, y, "N/A")
            y -= 14

        y -= 10

    # -------------------------
    # SECTIONS
    # -------------------------
    section("Professional Summary", cv.professional_summary)
    section("Skills", cv.skills)
    section("Experience", cv.experience)
    section("Education", cv.education)

    # -------------------------
    # FOOTER LINE
    # -------------------------
    y -= 20
    p.line(x, y, width - 60, y)

    p.setFont("Times-Italic", 9)
    p.drawString(x, y - 15, "Generated by AI CV Builder")

    p.showPage()
    p.save()

    return response


# ---------------------------------------------------
# Helper
# ---------------------------------------------------

def draw_wrapped_text(pdf, text, x, y, width=90, line_height=14):
    """
    Draws multi-line text.
    This is a simple implementation that we'll improve later.
    """

    if not text:
        pdf.drawString(x, y, "N/A")
        return y - line_height

    for line in text.split("\n"):
        pdf.drawString(x, y, line[:width])
        y -= line_height

    return y


# ---------------------------------------------------
# MODERN TEMPLATE
# ---------------------------------------------------

def render_modern_pdf(cv):

    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        f'attachment; filename="{cv.full_name}_Modern.pdf"'
    )

    pdf = canvas.Canvas(response, pagesize=A4)

    width, height = A4

    # -------------------------
    # Blue sidebar
    # -------------------------

    sidebar_width = 160

    pdf.setFillColor(colors.HexColor("#1E3A8A"))
    pdf.rect(0, 0, sidebar_width, height, fill=True, stroke=False)

    pdf.setFillColor(colors.white)

    y = height - 60

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(20, y, "CONTACT")

    y -= 30

    pdf.setFont("Helvetica", 10)
    pdf.drawString(20, y, cv.email or "")
    y -= 18

    pdf.drawString(20, y, cv.phone or "")
    y -= 18

    pdf.drawString(20, y, cv.address or "")

    y -= 45

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(20, y, "SKILLS")

    y -= 25

    pdf.setFont("Helvetica", 10)

    if cv.skills:
        for skill in cv.skills.split("\n"):
            pdf.drawString(20, y, "• " + skill)
            y -= 16

    # -------------------------
    # Main section
    # -------------------------

    x = 190
    y = height - 60

    pdf.setFillColor(colors.black)

    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawString(x, y, cv.full_name)

    y -= 30

    pdf.setFont("Helvetica", 14)
    pdf.drawString(x, y, cv.job_title or "")

    y -= 45

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(x, y, "Professional Summary")

    y -= 22

    pdf.setFont("Helvetica", 10)
    y = draw_wrapped_text(pdf, cv.professional_summary, x, y)

    y -= 20

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(x, y, "Experience")

    y -= 22

    pdf.setFont("Helvetica", 10)
    y = draw_wrapped_text(pdf, cv.experience, x, y)

    y -= 20

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(x, y, "Education")

    y -= 22

    pdf.setFont("Helvetica", 10)
    draw_wrapped_text(pdf, cv.education, x, y)

    pdf.save()

    return response


# ---------------------------------------------------
# CLASSIC TEMPLATE
# (placeholder for next step)
# ---------------------------------------------------

def render_classic_pdf(cv):

    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        f'attachment; filename="{cv.full_name}_Classic.pdf"'
    )

    pdf = canvas.Canvas(response, pagesize=A4)

    width, height = A4

    y = height - 60

    # ------------------------------------------------
    # HEADER
    # ------------------------------------------------

    pdf.setFont("Helvetica-Bold", 26)
    pdf.drawCentredString(width / 2, y, cv.full_name)

    y -= 25

    pdf.setFont("Helvetica", 14)
    pdf.drawCentredString(width / 2, y, cv.job_title or "")

    y -= 20

    pdf.setFont("Helvetica", 10)

    contact = " | ".join(filter(None, [
        cv.email,
        cv.phone,
        cv.address
    ]))

    pdf.drawCentredString(width / 2, y, contact)

    y -= 35

    pdf.line(50, y, width - 50, y)

    y -= 35

    # ------------------------------------------------
    # PROFESSIONAL SUMMARY
    # ------------------------------------------------

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, y, "Professional Summary")

    y -= 22

    pdf.setFont("Helvetica", 11)
    y = draw_wrapped_text(pdf, cv.professional_summary, 50, y)

    y -= 20

    # ------------------------------------------------
    # EXPERIENCE
    # ------------------------------------------------

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, y, "Experience")

    y -= 22

    pdf.setFont("Helvetica", 11)
    y = draw_wrapped_text(pdf, cv.experience, 50, y)

    y -= 20

    # ------------------------------------------------
    # EDUCATION
    # ------------------------------------------------

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, y, "Education")

    y -= 22

    pdf.setFont("Helvetica", 11)
    y = draw_wrapped_text(pdf, cv.education, 50, y)

    y -= 20

    # ------------------------------------------------
    # SKILLS
    # ------------------------------------------------

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, y, "Skills")

    y -= 22

    pdf.setFont("Helvetica", 11)

    if cv.skills:

        for skill in cv.skills.split("\n"):
            pdf.drawString(60, y, f"• {skill}")
            y -= 16

    pdf.save()

    return response


# ---------------------------------------------------
# EXECUTIVE TEMPLATE
# (placeholder for next step)
# ---------------------------------------------------

def render_executive_pdf(cv):

    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        f'attachment; filename="{cv.full_name}_Executive.pdf"'
    )

    pdf = canvas.Canvas(response, pagesize=A4)

    width, height = A4

    # ------------------------------------------------
    # DARK HEADER
    # ------------------------------------------------

    pdf.setFillColor(colors.HexColor("#2C3E50"))
    pdf.rect(0, height - 110, width, 110, fill=True, stroke=False)

    pdf.setFillColor(colors.white)

    pdf.setFont("Helvetica-Bold", 28)
    pdf.drawString(50, height - 50, cv.full_name)

    pdf.setFont("Helvetica", 14)
    pdf.drawString(50, height - 75, cv.job_title or "")

    pdf.setFont("Helvetica", 10)

    contact = " | ".join(filter(None, [
        cv.email,
        cv.phone,
        cv.address
    ]))

    pdf.drawString(50, height - 95, contact)

    # ------------------------------------------------
    # BODY
    # ------------------------------------------------

    pdf.setFillColor(colors.black)

    y = height - 150

    # Professional Summary
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, y, "Professional Profile")

    y -= 24

    pdf.setFont("Helvetica", 11)
    y = draw_wrapped_text(pdf, cv.professional_summary, 50, y)

    y -= 22

    # Experience
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, y, "Professional Experience")

    y -= 24

    pdf.setFont("Helvetica", 11)
    y = draw_wrapped_text(pdf, cv.experience, 50, y)

    y -= 22

    # Skills
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, y, "Core Competencies")

    y -= 24

    pdf.setFont("Helvetica", 11)

    if cv.skills:
        for skill in cv.skills.split("\n"):
            pdf.drawString(60, y, "• " + skill)
            y -= 16

    y -= 20

    # Education
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, y, "Education")

    y -= 24

    pdf.setFont("Helvetica", 11)
    draw_wrapped_text(pdf, cv.education, 50, y)

    pdf.save()

    return response


def render_executive_pdf(cv):
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = f'attachment; filename="{cv.full_name}_Executive_CV.pdf"'

    p = canvas.Canvas(response, pagesize=A4)
    width, height = A4

    # -------------------------
    # LAYOUT SETTINGS
    # -------------------------
    left_x = 50
    right_x = 340
    y = height - 60

    # =========================
    # LEFT COLUMN (Sidebar)
    # =========================
    p.setFont("Helvetica-Bold", 16)
    p.drawString(left_x, y, cv.full_name or "No Name")

    y -= 20

    p.setFont("Helvetica", 10)
    p.drawString(left_x, y, cv.job_title or "")

    y -= 30

    # Contact placeholder (you can expand later)
    p.setFont("Helvetica-Bold", 11)
    p.drawString(left_x, y, "PROFILE")
    y -= 15

    p.setFont("Helvetica", 9)
    for line in (cv.address or "").split("\n"):
        p.drawString(left_x, y, line[:40])
        y -= 12

    if cv.email:
        p.drawString(left_x, y, cv.email)
        y -= 12

    if cv.phone:
        p.drawString(left_x, y, cv.phone)
        y -= 20

    # Skills block
    p.setFont("Helvetica-Bold", 11)
    p.drawString(left_x, y, "SKILLS")
    y -= 15

    p.setFont("Helvetica", 9)
    for line in (cv.skills or "").split("\n"):
        p.drawString(left_x, y, f"- {line[:40]}")
        y -= 12

    # =========================
    # RIGHT COLUMN (Main CV)
    # =========================
    y_right = height - 60

    def section(title, text, y_pos):
        p.setFont("Helvetica-Bold", 12)
        p.drawString(right_x, y_pos, title)
        y_pos -= 15

        p.setFont("Helvetica", 9)

        if text:
            for line in text.split("\n"):
                clean = line.strip()
                if clean:
                    p.drawString(right_x, y_pos, clean[:80])
                    y_pos -= 12
        else:
            p.drawString(right_x, y_pos, "N/A")
            y_pos -= 12

        y_pos -= 15
        return y_pos

    y_right = section("PROFESSIONAL SUMMARY", cv.professional_summary, y_right)
    y_right = section("EXPERIENCE", cv.experience, y_right)
    y_right = section("EDUCATION", cv.education, y_right)

    # Footer line
    p.line(50, 40, width - 50, 40)

    p.setFont("Helvetica-Oblique", 8)
    p.drawString(50, 25, "Generated by AI CV Builder - Executive Template")

    p.showPage()
    p.save()

    return response