from reportlab.lib import colors


def new_page_if_needed(pdf, y, height, top_margin=55):
    if y < 70:
        pdf.showPage()
        pdf.setFont("Helvetica", 9)
        return height - top_margin

    return y


def draw_footer(pdf, width, text="Generated by AI CV Builder"):
    pdf.setFillColor(colors.HexColor("#64748b"))
    pdf.setFont("Helvetica-Oblique", 8)
    pdf.drawCentredString(width / 2, 28, text)


def draw_wrapped_text(
    pdf,
    text,
    x,
    y,
    max_width,
    font_name="Helvetica",
    font_size=9,
    line_height=12,
    height=842,
):
    pdf.setFont(font_name, font_size)

    if not text:
        return y

    words = str(text).split()
    line = ""

    for word in words:
        test_line = f"{line} {word}".strip()

        if pdf.stringWidth(test_line, font_name, font_size) <= max_width:
            line = test_line
        else:
            y = new_page_if_needed(pdf, y, height)
            pdf.setFont(font_name, font_size)
            pdf.drawString(x, y, line)
            y -= line_height
            line = word

    if line:
        y = new_page_if_needed(pdf, y, height)
        pdf.setFont(font_name, font_size)
        pdf.drawString(x, y, line)
        y -= line_height

    return y


def draw_section(pdf, title, text, x, y, max_width, title_color="#2563eb"):
    if not text:
        return y

    pdf.setFillColor(colors.HexColor(title_color))
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(x, y, title.upper())

    y -= 8
    pdf.setStrokeColor(colors.HexColor("#d1d5db"))
    pdf.line(x, y, x + max_width, y)

    y -= 18
    pdf.setFillColor(colors.HexColor("#111827"))

    paragraphs = str(text).split("\n")

    for paragraph in paragraphs:
        paragraph = paragraph.strip()

        if not paragraph:
            y -= 6
            continue

        y = draw_wrapped_text(
            pdf,
            paragraph,
            x,
            y,
            max_width,
            font_name="Helvetica",
            font_size=9,
            line_height=12,
        )

        y -= 4

    return y - 10


def draw_bullets(pdf, text, x, y, max_width, font_size=9, line_height=12):
    if not text:
        return y

    lines = [line.strip() for line in str(text).split("\n") if line.strip()]

    for line in lines:
        clean_line = line.replace("•", "", 1).strip()

        y = draw_wrapped_text(
            pdf,
            "•  " + clean_line,
            x,
            y,
            max_width,
            font_name="Helvetica",
            font_size=font_size,
            line_height=line_height,
        )

        y -= 4

    return y
