# Generated by Django 5.2.15 on 2026-07-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_uploads/'),
        ),
    ]
