# This generated Django migration records a database schema change.

# Generated by Django 5.2.15 on 2026-07-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_coverletter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cv",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="cv",
            name="uploaded_file",
        ),
        migrations.AddField(
            model_name="cv",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="job_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="professional_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="template",
            field=models.CharField(default="modern", max_length=50),
        ),
        migrations.AlterField(
            model_name="cv",
            name="education",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cv",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="cv",
            name="experience",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cv",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cv",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="CoverLetter",
        ),
    ]
