# Generated by Django 5.2.15 on 2026-07-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resumes",
            "0004_remove_cv_summary_remove_cv_uploaded_file_cv_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="template",
            field=models.CharField(
                choices=[
                    ("modern", "Modern"),
                    ("classic", "Classic"),
                    ("executive", "Executive"),
                ],
                default="modern",
                max_length=20,
            ),
        ),
    ]
