# Generated by Django 5.2.15 on 2026-07-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0006_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="cv_uploads/"),
        ),
    ]
