# Generated by Django 5.2.15 on 2026-07-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0007_cv_uploaded_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan_name",
            field=models.CharField(
                choices=[("Free", "Free"), ("Premium", "Premium")],
                default="Free",
                max_length=20,
            ),
        ),
    ]
